import { NextRequest } from "next/server";
import nodemailer from "nodemailer";

function reqEnv(name: string) {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env: ${name}`);
  return v;
}

export async function POST(req: NextRequest) {
  let body: { name?: string; email?: string; phone?: string };
  try {
    body = await req.json();
  } catch {
    return Response.json({ ok: false }, { status: 400 });
  }

  const { name = "", email = "", phone = "" } = body;
  if (!name || !email || !phone) {
    return Response.json({ ok: false, error: "Missing fields" }, { status: 400 });
  }

  const when = new Date().toLocaleString("en-US", { timeZone: "America/New_York" });

  try {
    const transporter = nodemailer.createTransport({
      host: reqEnv("SMTP_HOST"),
      port: Number(reqEnv("SMTP_PORT")),
      secure: String(reqEnv("SMTP_SECURE")) === "true",
      auth: { user: reqEnv("SMTP_USER"), pass: reqEnv("SMTP_PASS") },
    });

    await transporter.sendMail({
      from: reqEnv("MAIL_FROM"),
      to: reqEnv("MAIL_TO"),
      replyTo: email,
      subject: `Chat Lead: ${name}`,
      text:
        `New chat session started on teleringer.com\n\n` +
        `Name:  ${name}\n` +
        `Email: ${email}\n` +
        `Phone: ${phone}\n` +
        `Time:  ${when}\n`,
      html: `
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f3f5f7;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f3f5f7;">
    <tr><td align="center" style="padding:24px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"
             style="max-width:520px;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,.05);">
        <tr><td style="padding:24px 24px 8px;">
          <h1 style="margin:0;font-family:Arial,sans-serif;font-size:20px;color:#111827;">New Chat Lead</h1>
        </td></tr>
        <tr><td style="padding:8px 24px 16px;">
          <p style="margin:0 0 12px;font-family:Arial,sans-serif;font-size:14px;color:#374151;">
            A visitor just started a chat session on teleringer.com.
          </p>
          <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"
                 style="border:1px solid #e5e7eb;border-radius:8px;">
            <tr>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;background:#fafafa;width:80px;">Name</td>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;">${name}</td>
            </tr>
            <tr>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;background:#fafafa;">Email</td>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;">
                <a href="mailto:${email}" style="color:#2563eb;">${email}</a>
              </td>
            </tr>
            <tr>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;background:#fafafa;">Phone</td>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;">${phone}</td>
            </tr>
            <tr>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;background:#fafafa;">Time</td>
              <td style="padding:10px 14px;font-family:Arial,sans-serif;font-size:14px;color:#111827;">${when}</td>
            </tr>
          </table>
        </td></tr>
        <tr><td style="padding:0 24px 24px;">
          <p style="margin:0;font-family:Arial,sans-serif;font-size:12px;color:#9ca3af;">
            Generated by teleringer.com chat widget.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`,
    });
  } catch (err) {
    console.error("chat-lead email error:", err);
  }

  return Response.json({ ok: true });
}
